### ISSUE TITLE
how to build mouse PPI？

### ISSUE THREAD

**Issue by TangentDeng** [aet21/SCENT#4]
Great job! could you mind give some detail on how to build mouse protein PPI txt? Thanks!

**Comment by aet21** [comment]
There are two solutions to this:
(1) You can transform your mouse expression data set to human homologs and then use the human PPI. It turns out that features in the human PPI that correlate with stemness are "conserved" between species, specially mouse. You want to check Guo Guozhi's paper in Nat Genet. published in 2022 where they demonstrate the validity of SCENT/CCAT across multiple species.
(2) You build the mouse PPI following the strategy outlined for SCENT in the case of human PPI. Pathway commons I believe has the mouse-PPI resource.
BTW, SCENT/CCAT works about 80-90% of the time. In specific datasets it may not work, but this is true for any method trying to estimate differentiation potency as shown in our recent Bioinformatics CCAT paper.
Hope this helps
Andrew Teschendorff

**Comment by TangentDeng** [comment]
THANKS!

**Comment by nickhir** [comment]
> You want to check Guo Guozhi's paper in Nat Genet. published in 2022 where they demonstrate the validity of SCENT/CCAT across multiple species. 

Sorry to comment on this issue, but can you provide a link to that paper? I was unable to find it..
